-- DROP VIEW NONUNIQUEBARCODES_V;
CREATE VIEW NONUNIQUEBARCODES_V (CODE, BARCODE, WAREID, CHNG, INSCHNG, DELETED)
AS
SELECT s.CODE, b.BARCODE, b.WAREID, b.CHNG, b.INSCHNG, b.DELETED
FROM BARCODE b
JOIN SPRT s ON s.ID = b.WAREID
WHERE b.BARCODE IN (
    SELECT BARCODE
    FROM BARCODE
    GROUP BY BARCODE
    HAVING COUNT(*) > 1
);


